# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
print(np.__version__)

1.21.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2,3,5))
a

array([[[0.87279908, 0.73918221, 0.95955331, 0.32241967, 0.24645766],
        [0.62734502, 0.69473658, 0.21088412, 0.02781093, 0.97210964],
        [0.70958992, 0.60944509, 0.03866919, 0.04571601, 0.46815256]],

       [[0.06890482, 0.01426602, 0.05151702, 0.57400002, 0.698984  ],
        [0.75866066, 0.08391146, 0.99101027, 0.49606157, 0.94561589],
        [0.25368697, 0.47220946, 0.68217346, 0.24798748, 0.63600717]]])

In [4]:
# Method 2
a = np.random.rand(2,3,5)
a

array([[[0.10953089, 0.52464625, 0.32601352, 0.72316706, 0.85740004],
        [0.73448131, 0.74446267, 0.16293849, 0.54507208, 0.65864251],
        [0.31626451, 0.40399965, 0.47710353, 0.59047417, 0.46252433]],

       [[0.22100902, 0.24228811, 0.18576449, 0.78386422, 0.04460274],
        [0.46113918, 0.16583947, 0.98718784, 0.95899036, 0.79412589],
        [0.51989283, 0.22536535, 0.0910275 , 0.93897497, 0.28983794]]])

In [ ]:
# Method 3

#### 4. Print *a*.


In [5]:
# your code here
print(a)

[[[0.10953089 0.52464625 0.32601352 0.72316706 0.85740004]
  [0.73448131 0.74446267 0.16293849 0.54507208 0.65864251]
  [0.31626451 0.40399965 0.47710353 0.59047417 0.46252433]]

 [[0.22100902 0.24228811 0.18576449 0.78386422 0.04460274]
  [0.46113918 0.16583947 0.98718784 0.95899036 0.79412589]
  [0.51989283 0.22536535 0.0910275  0.93897497 0.28983794]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [6]:
b = np.ones((5,3,2))

#### 6. Print *b*.


In [7]:
b

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [11]:
print(b.size == a.size)

True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [9]:
a+b
# no se puede porque tienen diferentes dimensiones

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [13]:
c = np.transpose(b)

print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [14]:
d = a + c
print(d)
#Ahora fuciona porque tienen las mismas dimensiones

[[[1.10953089 1.52464625 1.32601352 1.72316706 1.85740004]
  [1.73448131 1.74446267 1.16293849 1.54507208 1.65864251]
  [1.31626451 1.40399965 1.47710353 1.59047417 1.46252433]]

 [[1.22100902 1.24228811 1.18576449 1.78386422 1.04460274]
  [1.46113918 1.16583947 1.98718784 1.95899036 1.79412589]
  [1.51989283 1.22536535 1.0910275  1.93897497 1.28983794]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [15]:
print(a)
print(d)

#los valores de d son los correspondientes a (a+1), esto es así porque c es un matriz de 1s

[[[0.10953089 0.52464625 0.32601352 0.72316706 0.85740004]
  [0.73448131 0.74446267 0.16293849 0.54507208 0.65864251]
  [0.31626451 0.40399965 0.47710353 0.59047417 0.46252433]]

 [[0.22100902 0.24228811 0.18576449 0.78386422 0.04460274]
  [0.46113918 0.16583947 0.98718784 0.95899036 0.79412589]
  [0.51989283 0.22536535 0.0910275  0.93897497 0.28983794]]]
[[[1.10953089 1.52464625 1.32601352 1.72316706 1.85740004]
  [1.73448131 1.74446267 1.16293849 1.54507208 1.65864251]
  [1.31626451 1.40399965 1.47710353 1.59047417 1.46252433]]

 [[1.22100902 1.24228811 1.18576449 1.78386422 1.04460274]
  [1.46113918 1.16583947 1.98718784 1.95899036 1.79412589]
  [1.51989283 1.22536535 1.0910275  1.93897497 1.28983794]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [16]:
e = a*c
print(e)

[[[0.10953089 0.52464625 0.32601352 0.72316706 0.85740004]
  [0.73448131 0.74446267 0.16293849 0.54507208 0.65864251]
  [0.31626451 0.40399965 0.47710353 0.59047417 0.46252433]]

 [[0.22100902 0.24228811 0.18576449 0.78386422 0.04460274]
  [0.46113918 0.16583947 0.98718784 0.95899036 0.79412589]
  [0.51989283 0.22536535 0.0910275  0.93897497 0.28983794]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [17]:
np.array_equal(a,e)
#

True

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [25]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max,d_min,d_mean)

1.9871878364940323 1.044602740663736 1.4848876977944923


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [26]:
f = np.empty((2,3,5))
f

array([[[ 25.,  75.,  25.,  75.,  75.],
        [ 75.,  75.,  25.,  75.,  75.],
        [ 25.,  25.,  25.,  75.,  25.]],

       [[ 25.,  25.,  25.,  75.,   0.],
        [ 25.,  25., 100.,  75.,  75.],
        [ 75.,  25.,  25.,  75.,  25.]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [30]:
# your code here
f[f==d_min] = 0

c25 = ((f > d_min) & (f < d_mean))
f[c25] = 25

f[f==d_mean] = 50

c75 = ((f > d_mean) & (f < d_max))
f[c75] = 75

f[f==d_max] = 100
                

In [31]:
d

array([[[1.10953089, 1.52464625, 1.32601352, 1.72316706, 1.85740004],
        [1.73448131, 1.74446267, 1.16293849, 1.54507208, 1.65864251],
        [1.31626451, 1.40399965, 1.47710353, 1.59047417, 1.46252433]],

       [[1.22100902, 1.24228811, 1.18576449, 1.78386422, 1.04460274],
        [1.46113918, 1.16583947, 1.98718784, 1.95899036, 1.79412589],
        [1.51989283, 1.22536535, 1.0910275 , 1.93897497, 1.28983794]]])

In [32]:
f

array([[[ 25.,  75.,  25.,  75.,  75.],
        [ 75.,  75.,  25.,  75.,  75.],
        [ 25.,  25.,  25.,  75.,  25.]],

       [[ 25.,  25.,  25.,  75.,   0.],
        [ 25.,  25., 100.,  75.,  75.],
        [ 75.,  25.,  25.,  75.,  25.]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here